name: Publish to PyPI

on:
  push:
    tags:
      - "v*" # Triggers on version tags like v1.0.0, v1.1.0, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi-token
    permissions:
      contents: read
      id-token: write # This is used for trusted publishing

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          python -m build

      - name: Check package
        run: |
          twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
