name: Publish to PyPI

on:
  push:
    tags:
      - "v*" # Triggers on version tags like v1.0.0, v1.1.0, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi-token
    permissions:
      contents: read
      id-token: write # This is used for trusted publishing

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Extract version from tag
        id: version
        run: |
          # Remove 'v' prefix from tag (e.g., v1.0.0 -> 1.0.0)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Update setup.py version
        run: |
          # Update setup.py with the tag version using Python for better reliability
          python -c "
          import re
          version = '${{ steps.version.outputs.version }}'
          with open('setup.py', 'r') as f:
              content = f.read()
          # Replace version line
          content = re.sub(r'version=\"[^\"]*\"', f'version=\"{version}\"', content)
          with open('setup.py', 'w') as f:
              f.write(content)
          print(f'Updated setup.py version to {version}')
          "

      - name: Build package
        run: |
          python -m build

      - name: Check package
        run: |
          twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
