name: Create Release

on:
  push:
    tags:
      - "v*" # Triggers on version tags like v1.0.0, v1.1.0, etc.

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for better changelog

      - name: Generate changelog
        id: changelog
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # Generate changelog from CHANGELOG.md
          if [ -f CHANGELOG.md ]; then
            # Extract changelog for this version
            awk "/^## \[$VERSION\]/{flag=1;next}/^## \[/{flag=0}flag" CHANGELOG.md > release_notes.md
          else
            echo "No changelog found" > release_notes.md
          fi

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.changelog.outputs.version }}
          body_path: release_notes.md
          draft: false
          prerelease: false
          fail_on_unmatched: false
